### ISSUE TITLE
Google offline cache for speed and reliability

### ISSUE THREAD

**Issue by Lillythefox** [Richienb/richienb.github.io#247]
look at this link [](https://developers.google.com/web/ilt/pwa/offline-quickstart)

**Comment by Lillythefox** [comment]
This link https://developers.google.com/web/ilt/pwa/offline-quickstart

<blockquote><img src="https://developers.google.com/web/images/social-webfu-16x9.png" width="48" align="right"><div>Google Developers</div><div><strong><a href="https://developers.google.com/web/ilt/pwa/offline-quickstart">Offline Quickstart  |  Web
       |  Google Developers</a></strong></div></blockquote>

**Comment by Richienb** [comment]
@Miner36 We have been using Service Workers and supported PWAs for at least a year now. Please analyse the files before asking something that we have already implemented.

Here is the [service-worker.js](https://github.com/Richienb/richienb.github.io/blob/master/service-worker.js) file that I've been using in case you are interested in that.

Thank you.
